local constants = {}

constants.fontAsset = "rbxassetid://12187375716"

constants.pillResizeInfo = TweenInfo.new(0.4, Enum.EasingStyle.Exponential, Enum.EasingDirection.Out)

constants.icons = {
    close = nil,
    minimise = nil,
    maximise = nil,
    settings = nil,
    search = nil,
    chevron = nil,
    check = nil,
    dot = nil,
    colorpicker = nil,
    config = nil,
    astra = nil,
}

constants.accent = {
    on = Color3.fromRGB(23, 153, 110),
    onStroke = Color3.fromRGB(32, 201, 144),
}

constants.statAccents = {
    positive = {
        fill = ColorSequence.new(Color3.fromRGB(0, 170, 127), Color3.fromRGB(0, 134, 98)),
        stroke = ColorSequence.new(Color3.fromRGB(0, 213, 156), Color3.fromRGB(0, 189, 135)),
    },
    negative = {
        fill = ColorSequence.new(Color3.fromRGB(172, 47, 47), Color3.fromRGB(135, 37, 37)),
        stroke = ColorSequence.new(Color3.fromRGB(255, 75, 75), Color3.fromRGB(244, 67, 67)),
    },
        neutral = {
        fill = ColorSequence.new(Color3.fromRGB(0, 170, 127), Color3.fromRGB(0, 134, 98)),
        stroke = ColorSequence.new(Color3.fromRGB(0, 213, 156), Color3.fromRGB(0, 189, 135)),
    },
}

constants.zIndex = {
        elementLock = 60,
    elementLockContent = 65,
    bottomFade = 100,
            notification = 1500,
    drag = 1000,
        toast = 2000,
    toastContent = 2001,
    restoreContent = 100001,
    restoreInteract = 100002,
}

constants.displayOrder = {
    window = 99999,
    
        popup = 100001,
}

return constants
